### ISSUE TITLE
Additional Libraries

### ISSUE THREAD

**Issue by cpabla** [AlbertGBena/RaProM-Pro#1]
Hello,

There are additional libraries that are required to run this script. You need matplotlib and numba.

**Comment by AlbertGBena** [comment]
Hi cpabla,
The script generates a netcdf file and it isn't necessary the libraries that you mencioned, but initially I used these libarries to test the results. Soon I'll upload a new version without theses libaries and with some new improvement.
Thanks for your comment.

**Comment by cpabla** [comment]
Hi. Thank you. Just to note the numba library is needed within miepython.

**Comment by AlbertGBena** [comment]
Hi cpabla,
I've checked the libraries vinculation and the results are:
Miepyhton--> Requires: matplotlib, numpy
netCDF4 -->Requires: cftime, numpy
So, in the next upload, I'll include this information.
Thanks for your comment.

**Comment by AlbertGBena** [comment]
Hi cpabla,
I've upload a new version, and in README I included the requirements from the libraries.
